debug: false

logging.level:
  org.springframework.cloud.kubernetes: DEBUG
  org.springframework.data: DEBUG
  org.springframework.web: DEBUG
  com.vmware.tanzulabs.app: DEBUG

server:
  port: 8081

spring:

  application:
    name: order-app

  mvc:
    log-request-details: true

management:
  endpoints:
    web.exposure.include: '*'
  endpoint:
    health:
      show-details: ALWAYS
